services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3000"
  ticket-service:
    build: ./ticket-service
    ports:
      - "3002:3000"
  user-service:
    build: ./user-service
    ports:
      - "3003:3000"
  notification-service:
    build: ./notification-service
    ports:
      - "3004:3000"
  reporting-service:
    build: ./reporting-service
    ports:
      - "3005:3000"
