services:
  auth-service:
    build: ./src/auth-service
    ports:
      - "3001:3001"
  ticket-service:
    build: ./src/ticket-service
    ports:
      - "3002:3002"
  user-service:
    build: ./src/user-service
    ports:
      - "3003:3003"
  notification-service:
    build: ./src/notification-service
    ports:
      - "3004:3004"
  reporting-service:
    build: ./src/reporting-service
    ports:
      - "3005:3005"